description: 'The account app is a simple app which provides all tools for a 3rd party developer to consume your API, it can be also easily embedded into an existing application.'
screenshot: 'https://www.fusio-project.org/media/apps/account.png'
website: 'https://github.com/apioo/fusio-apps-account'
