name: Build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '18.x'
      - name: Run install
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: account
          include-hidden-files: true
          path: dist/account
